### ISSUE TITLE
RuntimeError: Library libcublas.so.12 is not found

### ISSUE THREAD

**Issue by griffindodd** [rhasspy/wyoming-faster-whisper#30]
Ubuntu 20.84
CUDA 11.8
Nvidia Driver 525.147.05
Python 3.8
Pytorch 2.2.1+cu118
cuBLAS 11.11.3.6
cuDNN 8.7.0.84

The service works well enough when using CPU, but I  cannot get it to work with CUDA. Every guide I have have followed so far has used CUDA 11.8 but it seems that the version of cTranslate2 used in faster-whisper 1.0.0 now requires CUDA12 libraries.

On trying to use CUDA I get the Error: RuntimeError: Library libcublas.so.12 is not found

**Comment by super-qua** [comment]
I had the same problem. 

I was able to solve it by following the hint here https://github.com/SYSTRAN/faster-whisper/issues/516#issuecomment-1902687567 in order to add the correct virtual environment paths to the `LD_LIBRARY_PATH`

Steps (starting from your cloned folder)
```bash
source .venv/bin/activate
```
```bash
pip install nvidia-pyindex
pip install nvidia-cublas
pip install nvidia-cudnn
```
```bash
deactivate
```
```bash
export LD_LIBRARY_PATH=${PWD}/.venv/lib64/python3.11/site-packages/nvidia/cublas/lib:${PWD}/.venv/lib64/python3.11/site-packages/nvidia/cudnn/lib:$LD_LIBRARY_PATH
```
then it can be run with
```bash
script/run --model tiny-int8 --language en --uri 'tcp://0.0.0.0:10300' --data-dir /data --download-dir /data --device cuda
```

**Comment by rufinus** [comment]
see https://github.com/rhasspy/wyoming-faster-whisper/issues/35#issuecomment-2305540613 this is working currently.
